spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    username: ${mail.name}
    password: ${mail.password}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true




logging:
  level:
    org:
      springframework:
        security: DEBUG
        mail: DEBUG

base:
  url: https://8ab1-2a01-c23-6d19-1b00-7403-9e5c-d294-ee7b.ngrok-free.app
